In [1]:
import networkx as nx
from layout import Layout

In [2]:
# example graph and positions
G = nx.erdos_renyi_graph(10, 0.5)
pos = nx.spring_layout(G, dim=3)

# new layout instance
layout = Layout(G, pos)

In [7]:
pos

{0: array([ 0.41630483, -0.60637153, -0.39356789]),
 1: array([-0.97121667,  0.60195537, -0.67842684]),
 2: array([ 0.68429489, -0.35229333,  0.29065521]),
 3: array([-0.0847474 ,  0.08387068,  0.2872804 ]),
 4: array([-0.62226869,  0.41663172, -0.03077931]),
 5: array([-0.48652088, -0.40967634,  0.07141561]),
 6: array([-0.25966255,  0.12860308, -0.34926017]),
 7: array([0.13855721, 0.67022545, 0.17132314]),
 8: array([ 0.21122109, -1.        ,  0.11924673]),
 9: array([0.97403818, 0.46705491, 0.51211312])}

In [3]:
# prints node table
layout.node_table

          x         y         z   r    g    b    a    name
0  0.713285  0.235674  0.239269  31  119  180  100  node_0
1  0.000000  0.959125  0.000000  31  119  180  100  node_1
2  0.851051  0.387796  0.813985  31  119  180  100  node_2
3  0.455709  0.648937  0.811151  31  119  180  100  node_3
4  0.179384  0.848168  0.543995  31  119  180  100  node_4
5  0.249168  0.353440  0.629834  31  119  180  100  node_5
6  0.365790  0.675719  0.276485  31  119  180  100  node_6
7  0.570503  1.000000  0.713752  31  119  180  100  node_7
8  0.607858  0.000000  0.670010  31  119  180  100  node_8
9  1.000000  0.878357  1.000000  31  119  180  100  node_9

In [4]:
# prints edge table
layout.edge_table

    i  j  r  g  b    a
0   0  2  0  0  0  100
1   0  6  0  0  0  100
2   0  8  0  0  0  100
3   1  4  0  0  0  100
4   1  6  0  0  0  100
5   2  3  0  0  0  100
6   2  8  0  0  0  100
7   2  9  0  0  0  100
8   3  4  0  0  0  100
9   3  5  0  0  0  100
10  3  6  0  0  0  100
11  3  7  0  0  0  100
12  4  5  0  0  0  100
13  4  6  0  0  0  100
14  4  7  0  0  0  100
15  5  6  0  0  0  100
16  5  8  0  0  0  100
17  6  7  0  0  0  100
18  7  9  0  0  0  100

In [5]:
# shows a 3D preview of the layout
layout.preview(renderer= "browser")

In [6]:
# writes tables to nodes.csv and edges.csv
layout.write()